---
title: "COVID-19 Project -- Generate z scores for OD, OI"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r LoadData}
knitr::opts_chunk$set(
	fig.align = "center",
	fig.show = "hold",
	fig.showtext = TRUE,
	message = FALSE,
	warning = FALSE,
	cache = TRUE,
	comment = NA,
	results = "hold",
	tidy = F
)
library(bruceR)
library(psych)
library(ggpubr)
library(gridExtra)
library(tidyr)
library(kableExtra)
library(knitr)

########## read data
data <- read.csv("...",header = TRUE)

########## define variable names
demoinfo <- c("Group","NUM","GEN","EDU","AGE","AgeGroup","SMOKE","DRINK","reCAT","RTDATE","reRT")
testcat <- c("OD", "OI")

########## generate dataset for this analysis
data <- data[,c(demoinfo, testcat)]
subrows <- rownames(data)

########## generate different subsets
patientdata <- data[data$Group == 1,]#exclude the asymptomatic cases
controldata <- data[data$Group == 0,]

SavePath <- "..."
timsta <- format(Sys.time(),format = "%m%d%H%M")


```
# ***** Generate z Scores *****
## 1. Regress 
#### ** in OI
```{r regEDU, eval=TRUE}
# Sort
regtasklist <- c("OI")
lm_regress_p <- list()
lm_regress_c <- list()
data_reg <- data[,c(demoinfo,testcat)]
oridata_patient <- patientdata[,c("NUM","GEN","EDU","AgeGroup",regtasklist)] 
oridata_control <- controldata[,c("NUM","GEN","EDU","AgeGroup",regtasklist)]
Bs <- data.frame(tasks=regtasklist)
# Regression
for (taskn in 1:length(regtasklist)) {
  names(oridata_patient)[names(oridata_patient) == regtasklist[taskn]] <- "TEST"
  names(oridata_control)[names(oridata_control) == regtasklist[taskn]] <- "TEST"
  lm_regress_p[[regtasklist[taskn]]] <- lm(TEST~AgeGroup+EDU, oridata_patient)
  lm_regress_c[[regtasklist[taskn]]] <- lm(TEST~AgeGroup+EDU, oridata_control)
  Bs[taskn,"AGE_patient"] <- as.data.frame(lm_regress_p[[regtasklist[taskn]]]$coefficients)["AgeGroup",1]
  Bs[taskn,"AGE_control"] <- as.data.frame(lm_regress_c[[regtasklist[taskn]]]$coefficients)["AgeGroup",1]  
  Bs[taskn,"EDU_patient"] <- as.data.frame(lm_regress_p[[regtasklist[taskn]]]$coefficients)["EDU",1]
  Bs[taskn,"EDU_control"] <- as.data.frame(lm_regress_c[[regtasklist[taskn]]]$coefficients)["EDU",1]  
  names(oridata_patient)[names(oridata_patient) == "TEST"] <- regtasklist[taskn]
  names(oridata_control)[names(oridata_control) == "TEST"] <- regtasklist[taskn]
  for (subn in 1:length(subrows)) {
    # Patient
    if (data[subrows[subn],"Group"]==1){
      B_EDU <- as.data.frame(lm_regress_p[[regtasklist[taskn]]]$coefficients)["EDU",1]
      data_reg[subrows[subn],regtasklist[taskn]] <-  data[subrows[subn],regtasklist[taskn]] - B_EDU * (data[subrows[subn],"EDU"] - 12.23177)
    }
    # Control
    else {
      B_EDU <- as.data.frame(lm_regress_c[[regtasklist[taskn]]]$coefficients)["EDU",1]
      data_reg[subrows[subn],regtasklist[taskn]] <-  data[subrows[subn],regtasklist[taskn]] - B_EDU * (data[subrows[subn],"EDU"] - 12.23177)
    }
  }
}
```
#### ** in OD
```{r regDRINK, eval=TRUE}
# Sort
regtasklist <- c("OD")
oridata_patient <- patientdata[,c("NUM","SMOKE","DRINK","AgeGroup",regtasklist)] 
oridata_control <- controldata[,c("NUM","SMOKE","DRINK","AgeGroup",regtasklist)]
Bs[2,"tasks"] <- "OD"
# Regression
for (taskn in 1:length(regtasklist)) {
  names(oridata_patient)[names(oridata_patient) == regtasklist[taskn]] <- "TEST"
  names(oridata_control)[names(oridata_control) == regtasklist[taskn]] <- "TEST"
  lm_regress_p[[regtasklist[taskn]]] <- lm(TEST~AgeGroup + DRINK, oridata_patient)
  lm_regress_c[[regtasklist[taskn]]] <- lm(TEST~AgeGroup + DRINK, oridata_control)
  Bs[2,"AGE_patient"] <- as.data.frame(lm_regress_p[[regtasklist[taskn]]]$coefficients)["AgeGroup",1]
  Bs[2,"AGE_control"] <- as.data.frame(lm_regress_c[[regtasklist[taskn]]]$coefficients)["AgeGroup",1] 
  Bs[2,"DRINK_patient"] <- as.data.frame(lm_regress_p[[regtasklist[taskn]]]$coefficients)["DRINK",1]
  Bs[2,"DRINK_control"] <- as.data.frame(lm_regress_c[[regtasklist[taskn]]]$coefficients)["DRINK",1] 
  names(oridata_patient)[names(oridata_patient) == "TEST"] <- regtasklist[taskn]
  names(oridata_control)[names(oridata_control) == "TEST"] <- regtasklist[taskn]
  for (subn in 1:length(subrows)) {
    # Patient
    if (data[subrows[subn],"Group"]==1){
      B_DRINK <- as.data.frame(lm_regress_p[[regtasklist[taskn]]]$coefficients)["DRINK",1]
      data_reg[subrows[subn],regtasklist[taskn]] <-  data[subrows[subn],regtasklist[taskn]] - B_DRINK * (data[subrows[subn],"DRINK"] - 0)
    }
    # Control
    else {
      B_DRINK <- as.data.frame(lm_regress_c[[regtasklist[taskn]]]$coefficients)["DRINK",1]
      data_reg[subrows[subn],regtasklist[taskn]] <-  data[subrows[subn],regtasklist[taskn]]- B_DRINK * (data[subrows[subn],"DRINK"] - 0)
    }
  }
}
```
## 2. Adjust overflow values
```{r adjust}
data_reg$OD[data_reg$OD > 10] <- 10
data_reg$OI[data_reg$OI > 18] <- 18
```
## 3. Generate Bootstrap DataFrame
```{r bootstrap, eval=TRUE}
# Substitute task name when needed in testcat
TestsBoot <- data.frame(Tests = testcat, RepTim = numeric(length(testcat)), AG1_Mean = numeric(length(testcat)), AG1_SD = numeric(length(testcat)), AG2_Mean = numeric(length(testcat)), AG2_SD = numeric(length(testcat)), AG3_Mean = numeric(length(testcat)), AG3_SD = numeric(length(testcat)), AG4_Mean = numeric(length(testcat)), AG4_SD = numeric(length(testcat)), AG5_Mean = numeric(length(testcat)), AG5_SD = numeric(length(testcat)))#AG stands for age group
SamPoNum <- as.data.frame(table(controldata$AgeGroup))
colnames(SamPoNum) <- c("AgeGroup","Number")
RepTim <- 1000
TestsBoot$RepTim <- RepTim
tempdata <- data.frame(Mean=numeric(),SD=numeric())
for (testn in 1:length(testcat)) {
  #Extract Control Data to Bootstrap
    oridata <- data_reg[data_reg$Group==0,c("AgeGroup",testcat[testn])]
  # Age Group
  for (agn in 1:5) {
        agdata <- oridata[oridata$AgeGroup == agn,testcat[testn]]
      # Bootstrap
      for (repn in 1:RepTim) {
      sampleseq<- sample(1:length(agdata),SamPoNum[SamPoNum$AgeGroup==agn,"Number"],replace = TRUE)
      tempdata[repn,"Mean"] <- mean(agdata[sampleseq],na.rm = TRUE)
      tempdata[repn,"SD"] <- sd(agdata[sampleseq],na.rm = TRUE)
      }
      TestsBoot[testn,paste0("AG",agn,"_Mean",collapse = NULL)] <- mean(tempdata$Mean,na.rm = TRUE)
      TestsBoot[testn,paste0("AG",agn,"_SD",collapse = NULL)] <- mean(tempdata$SD,na.rm = TRUE)
  }
}
```
## 4. Calculate Z scores for patients and controls
```{r prepare_data}
# prepare dataframe z_data, all variables need to calculate were saved to z_data
z_data <- data[,c(demoinfo,testcat)]
# directly calculate z scores 
for (testn in 1:length(testcat)) {
    for (subn in 1:length(subrows)) {
    z_data[subrows[subn],testcat[testn]] <- (data_reg[subrows[subn],testcat[testn]]-TestsBoot[TestsBoot$Tests==testcat[testn],paste0("AG", data_reg[subrows[subn],"AgeGroup"], "_Mean", collapse = NULL)])/TestsBoot[TestsBoot$Tests==testcat[testn],paste0("AG", data_reg[subrows[subn],"AgeGroup"], "_SD", collapse = NULL)]
    }
}
```

## 5. Save
```{r export,eval=TRUE}
# save data_reg
ExcelFilePath <- paste0(SavePath,"data_OD&OI_reg_",timsta,".csv",collapse = NULL)
write.csv(data_reg,ExcelFilePath)
# save regression parameters
ExcelFilePath <- paste0(SavePath,"Bs_OD&OI_",timsta,".csv",collapse = NULL)
write.csv(Bs,ExcelFilePath)
# save bootstrap results
ExcelFileName <- paste0("Bootstrap_OD&OI_",timsta,".csv", collapse = NULL)
ExcelFilePath <- paste0(SavePath,ExcelFileName,collapse = NULL)
write.csv(TestsBoot,ExcelFilePath)
# save z score
ExcelFilePath <- paste0(SavePath,"z_score_OD&OI_",timsta,".csv",collapse = NULL)
write.csv(z_data,ExcelFilePath)
```





